#!/usr/bin/env bash

echo "[updatedeps] Old lock removed" &&
echo "[updatedeps] Checking updates" &&
./node_modules/.bin/ncu -u &&
echo "[updatedeps] Installing updates" &&
npm install &&
echo "[updatedeps] Dependencies updated successfully";
